name: Deploy to Zone.ee via FTPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Upload via FTPS
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: githubdeploy.siimsander.eu
          FTP_PASSWORD: "%gPh~4dBz49DL_;"
          FTP_SERVER_DIR: htdocs
        shell: bash
        run: |
          set -euo pipefail

          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" "ftps://$FTP_SERVER:21" <<EOF
          set ftp:ssl-force true
          set ftp:ssl-protect-data true
          set ssl:verify-certificate no
          set ftp:passive-mode true
          set net:timeout 30
          mkdir -p "$FTP_SERVER_DIR"
          cd "$FTP_SERVER_DIR"
          mirror -R --delete --verbose ./ .
          bye
          EOF

